// 短線操作日誌：標的日誌與進出明細分離，以 FIFO 計算已實現損益。
(function(){
  const $=id=>document.getElementById(id);let entries=[],fills=[],assets=[],activeId=null,mode="create";
  const auth=()=>window.ETFAuth,sb=()=>auth()&&auth().client(),user=()=>auth()&&auth().user();
  let editingFillId=null;
  const labels={planned:"計畫中",open:"持有中",closed:"已結束",cancelled:"取消"},marketLabel={tw:"台灣",us:"美國"},typeLabel={etf:"ETF",stock:"股票"};
  const identityIds=["assetType","market","symbol","assetName"],allHeaderIds=[...identityIds,"status","stopLoss","targetPrice","thesis","review"];
  const esc=s=>String(s==null?"":s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const num=n=>n==null?"—":Number(n).toLocaleString("en-US",{maximumFractionDigits:2}),money=n=>n==null?"—":Number(n).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2}),today=()=>new Date().toISOString().slice(0,10),normalize=s=>String(s||"").trim().toUpperCase();
  const feeRules={twCommission:.000399,twMinimumCommission:1,twStockTax:.003,twEtfTax:.001,usStockCommission:.0008,usEtfCommission:3,usSec:.0000206};
  const roundCent=n=>Math.round(n*100)/100,ceilCent=n=>Math.ceil((n-Number.EPSILON)*100)/100;
  function feeBreakdown(e,f){const value=(Number(f.shares)||0)*(Number(f.price)||0),manual=Number(f.brokerFee)||0,tw=e.market==="tw",commission=tw?Math.max(feeRules.twMinimumCommission,Math.round(value*feeRules.twCommission)):e.asset_type==="etf"?feeRules.usEtfCommission:roundCent(value*feeRules.usStockCommission);return{commission_native:manual>0?manual:(value>0?commission:0),tax_native:tw&&f.side==="sell"?value*(e.asset_type==="etf"?feeRules.twEtfTax:feeRules.twStockTax):0,regulatory_fee_native:!tw&&f.side==="sell"&&value>0?ceilCent(value*feeRules.usSec):0}}
  function feeTotal(f){return(Number(f.commission_native)||0)+(Number(f.tax_native)||0)+(Number(f.regulatory_fee_native)||0)}
  function feeText(e,f){const c=feeBreakdown(e,f);return"預估交易成本："+money(c.commission_native+c.tax_native+c.regulatory_fee_native)+" "+(e.market==="us"?"USD":"TWD")+"（手續費 "+money(c.commission_native)+"、稅／監管費 "+money(c.tax_native+c.regulatory_fee_native)+"）"}
  function updateFeePreview(){const e=entries.find(x=>String(x.id)===String(activeId));if(e&&mode==="fill")$("feePreview").textContent=feeText(e,readFill());}
  async function loadAssets(){try{const r=await fetch("trade_assets.json",{cache:"no-store"}),d=await r.json();assets=Array.isArray(d.assets)?d.assets:[]}catch(e){assets=[]}renderAssetOptions()}
  function renderAssetOptions(){const t=$("assetType").value,m=$("market").value;$("assetOptions").innerHTML=assets.filter(x=>x.asset_type===t&&x.market===m).map(x=>'<option value="'+esc(x.symbol)+'" label="'+esc(x.name)+'（'+esc(x.exchange)+'）"></option>').join("")}
  function fillAssetName(){const s=normalize($("symbol").value),x=assets.find(a=>a.asset_type===$("assetType").value&&a.market===$("market").value&&a.symbol===s);if(x)$("assetName").value=x.name}
  function gate(){const a=auth();if(!a||!a.isConfigured()){$("gate").style.display="block";$("app").style.display="none";$("gate").innerHTML='<div class="empty">會員功能尚未設定（需要 Supabase 設定）。</div>';return true}if(!a.user()){$("gate").style.display="block";$("app").style.display="none";$("gate").innerHTML='<div class="empty">請先登入，才能使用短線操作日誌。</div>';return true}$("gate").style.display="none";$("app").style.display="block";return false}
  async function load(){if(!sb()||!user())return;const [er,fr]=await Promise.all([sb().from("trade_journal_entries").select("*").order("created_at",{ascending:false}),sb().from("trade_journal_fills").select("*").order("fill_date",{ascending:true}).order("created_at",{ascending:true})]);entries=er.error?[]:(er.data||[]);fills=fr.error?[]:(fr.data||[]);render()}
  function fillsFor(id){return fills.filter(x=>String(x.journal_id)===String(id))}
  function fifo(rows){const lots=[],matches=[],open=[];let gross=0,cost=0,native=0,twd=0,valid=true;const ordered=rows.slice().sort((a,b)=>String(a.fill_date||"").localeCompare(String(b.fill_date||""))||String(a.created_at||"").localeCompare(String(b.created_at||""))||Number(a.id||0)-Number(b.id||0));ordered.forEach(f=>{let left=Number(f.shares)||0;if(f.side==="buy"){lots.push({fill:f,remaining:left});return}while(left>0){const lot=lots.find(x=>x.remaining>0);if(!lot){valid=false;break}const take=Math.min(left,lot.remaining),buy=lot.fill,sell=f,buyFx=buy.currency==="USD"?Number(buy.fx_rate)||null:1,sellFx=sell.currency==="USD"?Number(sell.fx_rate)||null:1,buyFee=feeTotal(buy)*(take/(Number(buy.shares)||1)),sellFee=feeTotal(sell)*(take/(Number(sell.shares)||1)),g=(Number(sell.price)-Number(buy.price))*take,n=g-buyFee-sellFee,t=buyFx&&sellFx?(Number(sell.price)*take*sellFx-Number(buy.price)*take*buyFx):null,ct=buyFx&&sellFx?(buyFee*buyFx+sellFee*sellFx):null;matches.push({buy,sell,shares:take,gross:g,cost:buyFee+sellFee,native:n,twd:t!=null&&ct!=null?t-ct:null,fx:sellFx});gross+=g;cost+=buyFee+sellFee;native+=n;if(t!=null&&ct!=null)twd+=t-ct;lot.remaining-=take;left-=take}});lots.filter(x=>x.remaining>0).forEach(x=>open.push({fill:x.fill,shares:x.remaining}));return{valid,matches,open,gross,cost,native,twd:twd||null}}
  function pnl(n){return n==null?"—":'<span class="'+(n>=0?"down":"up")+'">'+(n>=0?"+":"")+money(n)+"</span>"}
  function renderSummaryTotal(rows){const title=document.querySelector(".table-title");if(!title)return;let el=$("summaryTotal");if(!el){el=document.createElement("strong");el.id="summaryTotal";el.style.cssText="margin-left:auto;padding:6px 10px;border:1px solid var(--border);border-radius:8px;background:var(--bg);font-size:13px;white-space:nowrap";title.style.flexWrap="wrap";title.appendChild(el)}const matches=rows.filter(r=>r.m),valued=matches.filter(r=>r.m.twd!=null),total=valued.reduce((sum,r)=>sum+Number(r.m.twd),0);el.innerHTML='已實現總淨損益（TWD） '+(valued.length?pnl(total):"—")+(valued.length<matches.length?' <small style="color:var(--muted)">部分交易缺匯率</small>':"")}
  function summaryRows(){const rows=[];entries.forEach(e=>{const f=fifo(fillsFor(e.id));f.matches.forEach(m=>rows.push({e,m}));f.open.forEach(o=>rows.push({e,open:o}))});renderSummaryTotal(rows);return rows}
  function renderSummary(){const body=$("summaryRows"),rows=summaryRows();$("summaryEmpty").style.display=rows.length?"none":"block";body.innerHTML=rows.map(r=>{const e=r.e;if(r.open)return '<tr><td><b>'+esc(e.asset_name||e.symbol)+'</b><br><span style="color:var(--muted)">'+esc(e.symbol)+' · '+typeLabel[e.asset_type]+' · '+marketLabel[e.market]+'</span></td><td>'+esc(r.open.fill.fill_date)+'</td><td>—</td><td>'+num(r.open.shares)+'</td><td>'+money(r.open.fill.price)+'</td><td>—</td><td>'+esc(r.open.fill.currency||"TWD")+'</td><td>未實現</td><td>—</td><td>—</td><td>'+((r.open.fill.currency==="USD")?money(r.open.fill.fx_rate):"—")+'</td><td>—</td><td>'+labels[e.status]+'</td></tr>';const m=r.m;return '<tr><td><b>'+esc(e.asset_name||e.symbol)+'</b><br><span style="color:var(--muted)">'+esc(e.symbol)+' · '+typeLabel[e.asset_type]+' · '+marketLabel[e.market]+'</span></td><td>'+esc(m.buy.fill_date)+'</td><td>'+esc(m.sell.fill_date)+'</td><td>'+num(m.shares)+'</td><td>'+money(m.buy.price)+'</td><td>'+money(m.sell.price)+'</td><td>'+esc(m.sell.currency||"TWD")+'</td><td>'+pnl(m.gross)+'</td><td>'+money(m.cost)+'</td><td class="pnl-cell">'+pnl(m.native)+'</td><td>'+((m.sell.currency==="USD")?money(m.fx):"—")+'</td><td class="pnl-cell">'+pnl(m.twd)+'</td><td>已實現</td></tr>'}).join("")}
  function renderDetailFills(){if(!activeId)return;const fs=fillsFor(activeId);$("detailFills").innerHTML=fs.length?fs.map(x=>'<div class="fill-row"><span class="'+x.side+'">'+(x.side==="buy"?"買進":"賣出")+'</span><b>'+esc(x.fill_date)+'</b><span>'+num(x.shares)+' 股</span><span>@ '+money(x.price)+' '+x.currency+'</span><span>成本 '+money(feeTotal(x))+'</span><span class="fill-actions"><button class="ghost" data-edit-fill="'+esc(x.id)+'">修改</button> <button class="ghost danger" data-delete-fill="'+esc(x.id)+'">刪除</button></span></div>').join(""):'<div class="empty">尚未加入進出明細。</div>';document.querySelectorAll("[data-edit-fill]").forEach(b=>b.onclick=()=>editFill(b.dataset.editFill));document.querySelectorAll("[data-delete-fill]").forEach(b=>b.onclick=()=>removeFill(b.dataset.deleteFill))}
  function card(e){const fs=fillsFor(e.id),f=fifo(fs),currency=e.market==="us"?"USD":"TWD";return '<article class="entry"><div class="entry-top"><strong>'+esc(e.asset_name||e.symbol)+'</strong><span class="date">'+esc(e.symbol)+' · '+marketLabel[e.market]+'</span><span class="badge">'+typeLabel[e.asset_type]+'</span><span class="badge">'+marketLabel[e.market]+'</span><span class="badge '+(e.status==="closed"?"closed":"")+'">'+labels[e.status]+'</span><span class="entry-actions"><button class="primary" data-add-fill="'+esc(e.id)+'">進出明細維護</button><button data-edit="'+esc(e.id)+'">查看／編輯日誌</button><button class="danger" data-delete-entry="'+esc(e.id)+'">刪除</button></span></div><div class="facts"><span>明細 <b>'+fs.length+' 筆</b></span><span>已實現淨損益 '+currency+" "+pnl(f.native)+'</span><span>交易成本 '+currency+" "+money(f.cost)+'</span><span>台幣淨損益 '+pnl(f.twd)+'</span><span>未平倉 <b>'+num(f.open.reduce((s,x)=>s+x.shares,0))+' 股</b></span></div>'+(e.thesis?'<div class="thesis">📌 '+esc(e.thesis)+'</div>':'')+'</article>'}
  function render(){if(gate())return;const q=$("filterCode").value.trim().toUpperCase(),t=$("filterType").value,m=$("filterMarket").value,s=$("filterStatus").value,visible=entries.filter(e=>(!q||String(e.symbol||"").toUpperCase().includes(q)||String(e.asset_name||"").toUpperCase().includes(q))&&(!t||e.asset_type===t)&&(!m||e.market===m)&&(!s||e.status===s));$("summary").textContent=visible.length+" / "+entries.length+" 筆";$("empty").style.display=visible.length?"none":"block";$("entries").innerHTML=visible.map(card).join("");renderSummary();renderDetailFills();document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll("[data-add-fill]").forEach(b=>b.onclick=()=>openFill(b.dataset.addFill));document.querySelectorAll("[data-delete-entry]").forEach(b=>b.onclick=()=>removeEntry(b.dataset.deleteEntry))}
  function readHeader(){return{asset_type:$("assetType").value,market:$("market").value,symbol:normalize($("symbol").value),asset_name:$("assetName").value.trim()||null,status:$("status").value,stop_loss:$("stopLoss").value===""?null:Number($("stopLoss").value),target_price:$("targetPrice").value===""?null:Number($("targetPrice").value),thesis:$("thesis").value.trim()||null,review:$("review").value.trim()||null,action:"watch",trade_date:today(),updated_at:new Date().toISOString()}}
  function readFill(){return{fill_date:$("fillDate").value||null,side:$("fillSide").value,shares:$("fillShares").value===""?null:Number($("fillShares").value),price:$("fillPrice").value===""?null:Number($("fillPrice").value),brokerFee:$("brokerFee").value===""?0:Number($("brokerFee").value)}}
  function populate(e){const map={assetType:"asset_type",market:"market",symbol:"symbol",assetName:"asset_name",status:"status",stopLoss:"stop_loss",targetPrice:"target_price",thesis:"thesis",review:"review"};Object.keys(map).forEach(k=>$(k).value=e[map[k]]==null?"":e[map[k]]);renderAssetOptions();$("detailTitle").textContent=e.asset_name||e.symbol;$("detailIdentity").textContent=e.symbol+" · "+typeLabel[e.asset_type]+" · "+marketLabel[e.market]+" · "+labels[e.status];$("fillContext").textContent="目前正在記錄："+e.symbol+"（"+(e.asset_name||e.symbol)+" · "+marketLabel[e.market]+"）"}
  function setDisabled(disabled,lockIdentity){allHeaderIds.forEach(id=>$(id).disabled=disabled);identityIds.forEach(id=>$(id).disabled=lockIdentity)}
  function setMode(next){mode=next;const create=next==="create",edit=next==="edit",fill=next==="fill";$("homeScreen").classList.toggle("active",false);$("detailScreen").classList.toggle("active",true);$("formTitle").textContent=create?"建立標的日誌":edit?"日誌資訊":"進出明細維護模式";$("formHint").textContent=create?"先建立標的，再到該標的頁面維護買進／賣出明細。":edit?"這裡只更新日誌資訊，不會新增進出明細。":"目前標的已鎖定，可新增或修改下方進出明細。";$("submitBtn").style.display=fill?"none":"inline-block";$("submitBtn").textContent=create?"建立標的日誌":"更新日誌資訊";$("startFillBtn").style.display=!create&&!fill?"inline-block":"none";$("fillPanel").style.display=fill?"block":"none";$("detailLock").style.display=fill||(!create&&fillsFor(activeId).length)?"inline-block":"none";$("cancelBtn").textContent="回到清單";setDisabled(fill,fill||(!create&&fillsFor(activeId).length));renderDetailFills();updateFeePreview()}
  function goHome(){activeId=null;editingFillId=null;mode="create";$("detailScreen").classList.remove("active");$("homeScreen").classList.add("active");$("journalForm").reset();$("fillDate").value=today();$("brokerFee").value="";$("fillPanel").style.display="none";$("addFillBtn").textContent="新增進出明細";setDisabled(false,false);}
  function newEntry(){activeId=null;editingFillId=null;$("journalForm").reset();$("fillDate").value=today();$("brokerFee").value="";$("formMsg").textContent="";$("fillMsg").textContent="";setMode("create");window.scrollTo({top:0,behavior:"smooth"})}
  async function saveHeader(ev){ev.preventDefault();if(mode==="fill")return;const create=mode==="create",msg=$("formMsg"),header=readHeader();if(!/^[0-9A-Z.\-]{1,12}$/.test(header.symbol)){msg.textContent="代號格式不正確（可輸入清單外股票／ETF）";return}msg.style.color="var(--muted)";msg.textContent=create?"建立日誌中…":"更新日誌資訊中…";const r=create?await sb().from("trade_journal_entries").insert({...header,user_id:user().id}).select().single():await sb().from("trade_journal_entries").update(header).eq("id",activeId).eq("user_id",user().id);if(r.error){msg.style.color="var(--up)";msg.textContent="儲存失敗："+r.error.message;return}activeId=create?r.data.id:activeId;await load();const e=entries.find(x=>String(x.id)===String(activeId));if(e)populate(e);setMode("edit");msg.style.color="var(--down)";msg.textContent=create?"已建立標的日誌，請按「新增進出明細」開始記錄。":"日誌資訊已更新。"}
  async function fetchFx(){const r=await fetch("https://open.er-api.com/v6/latest/USD",{cache:"no-store"});if(!r.ok)throw Error("匯率服務無法連線");const d=await r.json(),rate=Number(d?.rates?.TWD);if(!rate||!Number.isFinite(rate))throw Error("匯率資料無效");return rate}
  async function addFillNew(){const msg=$("fillMsg"),e=entries.find(x=>String(x.id)===String(activeId)),fill=readFill();if(!e){msg.textContent="請先選擇一筆標的日誌。";return}if(!fill.fill_date||!fill.shares||fill.shares<=0||fill.price==null||fill.price<0||fill.brokerFee<0){msg.textContent="請填入明細日期、股數與成交價，費用不可為負數";return}msg.style.color="var(--muted)";msg.textContent=editingFillId?"更新明細中…":"儲存明細中…";const old=editingFillId?fills.find(x=>String(x.id)===String(editingFillId)):null;const test={...fill,...feeBreakdown(e,fill),currency:e.market==="us"?"USD":"TWD",fx_rate:e.market==="us"?(old?.fx_rate||null):1};delete test.brokerFee;if(test.currency==="USD"){msg.textContent="查詢 USD/TWD 匯率中…";try{test.fx_rate=await fetchFx();test.fx_fetched_at=new Date().toISOString()}catch(err){msg.style.color="var(--up)";msg.textContent="無法取得 USD/TWD 匯率，請稍後再試。";return}}const candidate={...test,id:editingFillId||Date.now(),created_at:old?.created_at||new Date().toISOString()};const base=editingFillId?fillsFor(activeId).filter(x=>String(x.id)!==String(editingFillId)):fillsFor(activeId);if(!fifo(base.concat(candidate)).valid){msg.style.color="var(--up)";msg.textContent="賣出股數超過目前 FIFO 可賣股數。";return}const r=editingFillId?await sb().from("trade_journal_fills").update(test).eq("id",editingFillId).eq("journal_id",activeId).eq("user_id",user().id):await sb().from("trade_journal_fills").insert({...test,journal_id:activeId,user_id:user().id});if(r.error){msg.style.color="var(--up)";msg.textContent=(editingFillId?"更新":"儲存")+"明細失敗："+r.error.message;return}const wasEditing=Boolean(editingFillId);editingFillId=null;await load();const latest=entries.find(x=>String(x.id)===String(activeId));if(latest)await syncParent(latest);await load();$("fillDate").value=today();$("fillShares").value="";$("fillPrice").value="";$("brokerFee").value="";$("addFillBtn").textContent="新增進出明細";msg.style.color="var(--down)";msg.textContent=(wasEditing?"明細已修改":"明細已新增")+"，目前仍在「"+e.symbol+"」這筆日誌中。";}
  async function addFill(){const msg=$("fillMsg"),e=entries.find(x=>String(x.id)===String(activeId)),fill=readFill();if(!e){msg.textContent="請先選擇一筆標的日誌。";return}if(!fill.fill_date||!fill.shares||fill.shares<=0||fill.price==null||fill.price<0||fill.brokerFee<0){msg.textContent="請填入明細日期、股數與成交價，費用不可為負數";return}msg.style.color="var(--muted)";msg.textContent="儲存明細中…";const test={...fill,...feeBreakdown(e,fill),currency:e.market==="us"?"USD":"TWD",fx_rate:e.market==="us"?null:1};delete test.brokerFee;if(test.currency==="USD"){msg.textContent="查詢 USD/TWD 匯率中…";try{test.fx_rate=await fetchFx();test.fx_fetched_at=new Date().toISOString()}catch(err){msg.style.color="var(--up)";msg.textContent="無法取得 USD/TWD 匯率，請稍後再試。";return}}if(!fifo(fillsFor(activeId).concat({...test,id:Date.now(),created_at:new Date().toISOString()})).valid){msg.style.color="var(--up)";msg.textContent="賣出股數超過目前 FIFO 可賣股數。";return}const r=await sb().from("trade_journal_fills").insert({...test,journal_id:activeId,user_id:user().id});if(r.error){msg.style.color="var(--up)";msg.textContent="儲存明細失敗："+r.error.message;return}await load();const latest=entries.find(x=>String(x.id)===String(activeId));if(latest)await syncParent(latest);await load();$("fillDate").value=today();$("fillShares").value="";$("fillPrice").value="";$("brokerFee").value="";msg.style.color="var(--down)";msg.textContent="明細已新增，目前仍在「"+e.symbol+"」這筆日誌中。";}
  async function syncParent(e){const fs=fillsFor(e.id),f=fifo(fs),b=fs.filter(x=>x.side==="buy"),s=fs.filter(x=>x.side==="sell");await sb().from("trade_journal_entries").update({entry_date:b.length?b.map(x=>x.fill_date).sort()[0]:null,exit_date:s.length?s.map(x=>x.fill_date).sort().slice(-1)[0]:null,pnl_native:f.native,pnl_twd:f.twd}).eq("id",e.id).eq("user_id",user().id)}
  function edit(id){const e=entries.find(x=>String(x.id)===String(id));if(!e)return;activeId=e.id;populate(e);setMode("edit");window.scrollTo({top:0,behavior:"smooth"})}
  function openFill(id){const e=entries.find(x=>String(x.id)===String(id));if(!e)return;activeId=e.id;editingFillId=null;populate(e);$("fillDate").value=today();$("fillShares").value="";$("fillPrice").value="";$("brokerFee").value="";$("fillMsg").textContent="";$("addFillBtn").textContent="新增進出明細";setMode("fill");window.scrollTo({top:0,behavior:"smooth"})}
  function editFill(id){const f=fills.find(x=>String(x.id)===String(id));if(!f)return;editingFillId=f.id;$("fillDate").value=f.fill_date||"";$("fillSide").value=f.side||"buy";$("fillShares").value=f.shares==null?"":f.shares;$("fillPrice").value=f.price==null?"":f.price;$("brokerFee").value="";$("fillMsg").textContent="正在修改這筆進出明細。若有手動佣金，請重新填入。";$("addFillBtn").textContent="儲存修改";updateFeePreview();$("fillDate").closest(".fill-grid").scrollIntoView({behavior:"smooth",block:"center"})}
  async function removeEntry(id){if(!confirm("確定刪除這筆操作日誌與所有進出明細？"))return;const r=await sb().from("trade_journal_entries").delete().eq("id",id).eq("user_id",user().id);if(r.error){alert("刪除失敗："+r.error.message);return}if(String(activeId)===String(id))goHome();await load()}
  async function removeFill(id){if(!confirm("確定刪除這筆進出明細？"))return;const r=await sb().from("trade_journal_fills").delete().eq("id",id).eq("user_id",user().id);if(r.error){alert("刪除失敗："+r.error.message);return}await load();const e=entries.find(x=>String(x.id)===String(activeId));if(e)await syncParent(e);await load()}
  document.addEventListener("DOMContentLoaded",()=>{goHome();loadAssets();$("journalForm").onsubmit=saveHeader;$("newEntryBtn").onclick=newEntry;$("startFillBtn").onclick=()=>openFill(activeId);$("addFillBtn").onclick=addFill;$("backBtn").onclick=goHome;$("cancelBtn").onclick=goHome;$("assetType").onchange=()=>{renderAssetOptions();fillAssetName()};$("market").onchange=()=>{renderAssetOptions();fillAssetName();updateFeePreview()};$("symbol").oninput=fillAssetName;$("fillSide").onchange=updateFeePreview;$("fillShares").oninput=updateFeePreview;$("fillPrice").oninput=updateFeePreview;$("brokerFee").oninput=updateFeePreview;$("filterCode").oninput=render;$("filterType").onchange=render;$("filterMarket").onchange=render;$("filterStatus").onchange=render;$("clearFilter").onclick=()=>{$("filterCode").value="";$("filterType").value="";$("filterMarket").value="";$("filterStatus").value="";render()}});document.addEventListener("etfwatch:change",()=>user()?load():gate());setTimeout(()=>user()?load():gate(),500)
  document.addEventListener("DOMContentLoaded",()=>{$("addFillBtn").onclick=addFillNew;const panel=$("fillPanel"),h=panel.querySelector("h3");if(h)h.textContent="進出明細維護（FIFO）";const b=$("startFillBtn");if(b)b.textContent="進出明細維護";const feeInput=$("brokerFee");feeInput.placeholder="空白採國泰預設";if(feeInput.parentNode.firstChild)feeInput.parentNode.firstChild.nodeValue="券商佣金（原幣，選填；空白採國泰預設）";const note=panel.querySelector(".sub");if(note)note.textContent="台股股票／ETF 手續費採國泰 0.0399%（最低 1 元）；美股採成交金額 0.08%，美國 ETF 每筆 3 美元，賣出另計交易徵費。"});
})();
