// 短線操作日誌：主檔＋多筆進出明細，以 FIFO 計算已實現損益。
(function () {
  const $ = (id) => document.getElementById(id);
  let entries = [], fills = [], assets = [], editingId = null;
  const auth = () => window.ETFAuth;
  const sb = () => auth() && auth().client();
  const user = () => auth() && auth().user();
  const labels = { planned:"計畫中", open:"持有中", closed:"已結束", cancelled:"取消" };
  const marketLabel = { tw:"台灣", us:"美國" }, typeLabel = { etf:"ETF", stock:"股票" };
  const esc = (s) => String(s == null ? "" : s).replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const num = (n) => n == null ? "—" : Number(n).toLocaleString("en-US", { maximumFractionDigits:2 });
  const money = (n) => n == null ? "—" : Number(n).toLocaleString("en-US", { minimumFractionDigits:2, maximumFractionDigits:2 });
  const today = () => new Date().toISOString().slice(0, 10);
  const normalizeSymbol = (s) => String(s || "").trim().toUpperCase();

  async function loadAssets() { try { const r = await fetch("trade_assets.json", { cache:"no-store" }); const d = await r.json(); assets = Array.isArray(d.assets) ? d.assets : []; } catch (e) { assets = []; } renderAssetOptions(); }
  function renderAssetOptions() { const type=$("assetType").value, market=$("market").value; $("assetOptions").innerHTML=assets.filter((x)=>x.asset_type===type&&x.market===market).map((x)=>'<option value="'+esc(x.symbol)+'" label="'+esc(x.name)+'（'+esc(x.exchange)+'）"></option>').join(""); }
  function fillAssetName() { const symbol=normalizeSymbol($("symbol").value); const x=assets.find((a)=>a.asset_type===$("assetType").value&&a.market===$("market").value&&a.symbol===symbol); if(x)$("assetName").value=x.name; }
  function gate() { const a=auth(); if(!a||!a.isConfigured()){ $("gate").style.display="block";$("app").style.display="none";$("gate").innerHTML='<div class="empty">會員功能尚未設定（需要 Supabase 設定）。</div>';return true; } if(!a.user()){ $("gate").style.display="block";$("app").style.display="none";$("gate").innerHTML='<div class="empty">請先登入，才能使用短線操作日誌。</div>';return true; } $("gate").style.display="none";$("app").style.display="block";return false; }
  async function load() { if(!sb()||!user())return; const [er,fr]=await Promise.all([sb().from("trade_journal_entries").select("*").order("created_at",{ascending:false}),sb().from("trade_journal_fills").select("*").order("fill_date",{ascending:true}).order("created_at",{ascending:true})]); entries=er.error?[]:(er.data||[]); fills=fr.error?[]:(fr.data||[]); render(); }
  function fillsFor(id) { return fills.filter((x)=>String(x.journal_id)===String(id)); }
  function fifo(rows) { const lots=[], matches=[], open=[]; let native=0, twd=0, valid=true; const ordered=rows.slice().sort((a,b)=>String(a.fill_date||"").localeCompare(String(b.fill_date||""))||String(a.created_at||"").localeCompare(String(b.created_at||""))||Number(a.id||0)-Number(b.id||0)); ordered.forEach((f)=>{ let left=Number(f.shares)||0; if(f.side==="buy"){lots.push({fill:f,remaining:left});return;} while(left>0){const lot=lots.find((x)=>x.remaining>0);if(!lot){valid=false;break;}const take=Math.min(left,lot.remaining), buy=lot.fill, sell=f, buyFx=buy.currency==="USD"?Number(buy.fx_rate)||null:1, sellFx=sell.currency==="USD"?Number(sell.fx_rate)||null:1;const n=(Number(sell.price)-Number(buy.price))*take;const t=buyFx&&sellFx?(Number(sell.price)*take*sellFx-Number(buy.price)*take*buyFx):null;matches.push({buy,sell,shares:take,native:n,twd:t,fx:sellFx});native+=n;if(t!=null)twd+=t;lot.remaining-=take;left-=take;}});lots.filter((x)=>x.remaining>0).forEach((x)=>open.push({fill:x.fill,shares:x.remaining}));return {valid,matches,open,native,twd:twd||null}; }
  function pnlLabel(n) { return n==null?"—":'<span class="'+(n>=0?"down":"up")+'">'+(n>=0?"+":"")+money(n)+'</span>'; }
  function summaryRows() { const rows=[]; entries.forEach((e)=>{const f=fifo(fillsFor(e.id));f.matches.forEach((m)=>rows.push({e,m,status:"closed"}));f.open.forEach((o)=>rows.push({e,open:o,status:e.status}));});return rows; }
  function renderSummaryTable() { const body=$("summaryRows"), rows=summaryRows(); $("summaryEmpty").style.display=rows.length?"none":"block"; body.innerHTML=rows.map((r)=>{const e=r.e;if(r.open)return '<tr><td><b>'+esc(e.asset_name||e.symbol)+'</b><br><span style="color:var(--muted)">'+esc(e.symbol)+' · '+typeLabel[e.asset_type]+' · '+marketLabel[e.market]+'</span></td><td>'+esc(r.open.fill.fill_date)+'</td><td>—</td><td>'+num(r.open.shares)+'</td><td>'+money(r.open.fill.price)+'</td><td>—</td><td>'+esc(r.open.fill.currency||"TWD")+'</td><td>未實現</td><td>'+((r.open.fill.currency==="USD")?money(r.open.fill.fx_rate):"—")+'</td><td>—</td><td>'+labels[e.status]+'</td></tr>';const m=r.m;return '<tr><td><b>'+esc(e.asset_name||e.symbol)+'</b><br><span style="color:var(--muted)">'+esc(e.symbol)+' · '+typeLabel[e.asset_type]+' · '+marketLabel[e.market]+'</span></td><td>'+esc(m.buy.fill_date)+'</td><td>'+esc(m.sell.fill_date)+'</td><td>'+num(m.shares)+'</td><td>'+money(m.buy.price)+'</td><td>'+money(m.sell.price)+'</td><td>'+esc(m.sell.currency||"TWD")+'</td><td class="pnl-cell">'+pnlLabel(m.native)+'</td><td>'+((m.sell.currency==="USD")?money(m.fx):"—")+'</td><td class="pnl-cell">'+pnlLabel(m.twd)+'</td><td>已實現</td></tr>';}).join(""); }
  function render() { if(gate())return; const q=$("filterCode").value.trim().toUpperCase(),type=$("filterType").value,market=$("filterMarket").value,status=$("filterStatus").value;const visible=entries.filter((e)=>(!q||String(e.symbol||"").toUpperCase().includes(q)||String(e.asset_name||"").toUpperCase().includes(q))&&(!type||e.asset_type===type)&&(!market||e.market===market)&&(!status||e.status===status));$("summary").textContent=visible.length+" / "+entries.length+" 筆";$("empty").style.display=visible.length?"none":"block";$("entries").innerHTML=visible.map(card).join("");renderSummaryTable();document.querySelectorAll("[data-edit]").forEach((b)=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll("[data-delete-entry]").forEach((b)=>b.onclick=()=>removeEntry(b.dataset.deleteEntry));document.querySelectorAll("[data-delete-fill]").forEach((b)=>b.onclick=()=>removeFill(b.dataset.deleteFill));}
  function card(e) { const fs=fillsFor(e.id), f=fifo(fs), currency=e.market==="us"?"USD":"TWD";return '<article class="entry"><div class="entry-top"><strong>'+esc(e.asset_name||e.symbol)+'</strong><span class="date">'+esc(e.symbol)+' · '+marketLabel[e.market]+'</span><span class="badge">'+typeLabel[e.asset_type]+'</span><span class="badge">'+marketLabel[e.market]+'</span><span class="badge '+(e.status==="closed"?"closed":"")+'">'+labels[e.status]+'</span><span class="entry-actions"><button data-edit="'+esc(e.id)+'">編輯</button><button class="delete" data-delete-entry="'+esc(e.id)+'">刪除</button></span></div><div class="facts"><span>明細 <b>'+fs.length+' 筆</b></span><span>已實現 '+(currency+" ")+pnlLabel(f.native)+'</span><span>台幣損益 '+pnlLabel(f.twd)+'</span><span>未平倉 <b>'+num(f.open.reduce((s,x)=>s+x.shares,0))+' 股</b></span></div>'+(e.thesis?'<div class="thesis">📌 '+esc(e.thesis)+'</div>':'')+'<div class="fill-list">'+(fs.length?fs.map((x)=>'<div class="fill-row"><span class="'+x.side+'">'+(x.side==="buy"?"買進":"賣出")+'</span><b>'+esc(x.fill_date)+'</b><span>'+num(x.shares)+' 股</span><span>@ '+money(x.price)+' '+x.currency+'</span><span class="fill-actions"><button class="delete" data-delete-fill="'+esc(x.id)+'">刪除</button></span></div>').join(""):'<div class="empty">尚未加入進出明細。</div>')+'</div>'+(e.review?'<div class="review">檢討：'+esc(e.review)+'</div>':'')+'</article>'; }
  async function fetchUsdTwd() { const r=await fetch("https://open.er-api.com/v6/latest/USD",{cache:"no-store"});if(!r.ok)throw new Error("匯率服務無法連線");const d=await r.json(),rate=Number(d&&d.rates&&d.rates.TWD);if(!rate||!Number.isFinite(rate))throw new Error("匯率資料無效");return rate; }
  function readHeader() { return {asset_type:$("assetType").value,market:$("market").value,symbol:normalizeSymbol($("symbol").value),asset_name:$("assetName").value.trim()||null,status:$("status").value,stop_loss:$("stopLoss").value===""?null:Number($("stopLoss").value),target_price:$("targetPrice").value===""?null:Number($("targetPrice").value),thesis:$("thesis").value.trim()||null,review:$("review").value.trim()||null,action:"watch",trade_date:today(),updated_at:new Date().toISOString()}; }
  function readFill() { const shares=$("fillShares").value===""?null:Number($("fillShares").value),price=$("fillPrice").value===""?null:Number($("fillPrice").value);return {fill_date:$("fillDate").value||null,side:$("fillSide").value,shares,price}; }
  async function addFill(journalId, fill, msg) { if(!fill.fill_date||!fill.shares||fill.shares<=0||fill.price==null||fill.price<0){msg.textContent="請填入明細日期、股數與成交價";return false;}const existing=fillsFor(journalId), test={...fill,currency:$("market").value==="us"?"USD":"TWD",fx_rate:$("market").value==="us"?null:1};if(test.currency==="USD"){msg.style.color="var(--muted)";msg.textContent="查詢 USD/TWD 匯率中…";try{test.fx_rate=await fetchUsdTwd();test.fx_fetched_at=new Date().toISOString();}catch(e){msg.style.color="var(--up)";msg.textContent="無法取得 USD/TWD 匯率，請稍後再試。";return false;}}const check=fifo(existing.concat({...test,created_at:new Date().toISOString(),id:Date.now()}));if(!check.valid){msg.style.color="var(--up)";msg.textContent="賣出股數超過目前 FIFO 可賣股數。";return false;}const r=await sb().from("trade_journal_fills").insert({...test,journal_id:journalId,user_id:user().id});if(r.error){msg.style.color="var(--up)";msg.textContent="儲存明細失敗："+r.error.message;return false;}return true; }
  async function syncParent(e) { const fs=fillsFor(e.id),f=fifo(fs),buys=fs.filter((x)=>x.side==="buy"),sells=fs.filter((x)=>x.side==="sell");const payload={entry_date:buys.length?buys.map((x)=>x.fill_date).sort()[0]:null,exit_date:sells.length?sells.map((x)=>x.fill_date).sort().slice(-1)[0]:null,pnl_native:f.native,pnl_twd:f.twd};await sb().from("trade_journal_entries").update(payload).eq("id",e.id).eq("user_id",user().id);}
  async function save(e) { e.preventDefault();const msg=$("formMsg"),header=readHeader();if(!/^[0-9A-Z.\-]{1,12}$/.test(header.symbol)){msg.textContent="代號格式不正確（可使用台股、美股常見代號）";return;}msg.style.color="var(--muted)";msg.textContent="儲存日誌中…";const r=editingId?await sb().from("trade_journal_entries").update(header).eq("id",editingId).eq("user_id",user().id):await sb().from("trade_journal_entries").insert({...header,user_id:user().id}).select().single();if(r.error){msg.style.color="var(--up)";msg.textContent="儲存失敗："+r.error.message;return;}const id=editingId||r.data.id;editingId=id;const fill=readFill();if(fill.fill_date||fill.shares!=null||fill.price!=null){const ok=await addFill(id,fill,msg);if(!ok)return;}await load();const current=entries.find((x)=>String(x.id)===String(id));if(current)await syncParent(current);await load();$("fillDate").value="";$("fillShares").value="";$("fillPrice").value="";$("formTitle").textContent="編輯操作日誌";$("submitBtn").textContent="更新日誌";$("cancelBtn").style.display="inline-block";msg.style.color="var(--down)";msg.textContent="已儲存。可繼續加入分批明細。";}
  function reset() {editingId=null;$("journalForm").reset();$("formTitle").textContent="新增操作日誌";$("submitBtn").textContent="儲存日誌";$("cancelBtn").style.display="none";$("formMsg").textContent="";$("fillDate").value=today();}
  function edit(id) {const e=entries.find((x)=>String(x.id)===String(id));if(!e)return;editingId=e.id;const fields={assetType:"asset_type",market:"market",symbol:"symbol",assetName:"asset_name",status:"status",stopLoss:"stop_loss",targetPrice:"target_price",thesis:"thesis",review:"review"};Object.keys(fields).forEach((k)=>$(k).value=e[fields[k]]==null?"":e[fields[k]]);$("formTitle").textContent="編輯操作日誌";$("submitBtn").textContent="更新日誌";$("cancelBtn").style.display="inline-block";renderAssetOptions();window.scrollTo({top:0,behavior:"smooth"});}
  async function removeEntry(id) {if(!confirm("確定刪除這筆操作日誌與所有進出明細？"))return;const r=await sb().from("trade_journal_entries").delete().eq("id",id).eq("user_id",user().id);if(r.error){alert("刪除失敗："+r.error.message);return;}if(String(editingId)===String(id))reset();await load();}
  async function removeFill(id) {if(!confirm("確定刪除這筆進出明細？"))return;const r=await sb().from("trade_journal_fills").delete().eq("id",id).eq("user_id",user().id);if(r.error){alert("刪除失敗："+r.error.message);return;}await load();}
  document.addEventListener("DOMContentLoaded",()=>{reset();loadAssets();$("journalForm").onsubmit=save;$("addFillBtn").onclick=()=>$("journalForm").requestSubmit();$("cancelBtn").onclick=reset;$("assetType").onchange=()=>{renderAssetOptions();fillAssetName();};$("market").onchange=()=>{renderAssetOptions();fillAssetName();};$("symbol").oninput=fillAssetName;$("filterCode").oninput=render;$("filterType").onchange=render;$("filterMarket").onchange=render;$("filterStatus").onchange=render;$("clearFilter").onclick=()=>{$("filterCode").value="";$("filterType").value="";$("filterMarket").value="";$("filterStatus").value="";render();};});
  document.addEventListener("etfwatch:change",()=>{if(user())load();else gate();});setTimeout(()=>{if(user())load();else gate();},500);
})();
